CREATE TABLE IF NOT EXISTS client (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    CHECK(LENGTH(name) > 2)
);

CREATE TABLE IF NOT EXISTS planet (
    id VARCHAR(30) PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    CHECK(LENGTH(name) > 0)
);

CREATE TABLE IF NOT EXISTS ticket (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    client_id BIGINT REFERENCES client(id) ON DELETE CASCADE NOT NULL,
    from_planet_id VARCHAR(30) REFERENCES planet(id) ON DELETE CASCADE NOT NULL,
    to_planet_id VARCHAR(30) REFERENCES planet(id) ON DELETE CASCADE NOT NULL
);